-- Revert NULL timestamp columns back to NOT NULL with defaults
-- This reverts the schema back to the original design

-- Revert domains table
ALTER TABLE domains 
MODIFY COLUMN created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Revert users table  
ALTER TABLE users
MODIFY COLUMN created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Revert aliases table
ALTER TABLE aliases
MODIFY COLUMN created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Revert backups table
ALTER TABLE backups
MODIFY COLUMN created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Revert relays table
ALTER TABLE relays
MODIFY COLUMN created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Revert relocated table
ALTER TABLE relocated
MODIFY COLUMN created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY COLUMN modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
