use askama::Template;

#[derive(Template)]
#[template(path = "about.html", escape = "html")]
pub struct AboutTemplate<'a> {
    pub title: &'a str,
    pub subtitle: &'a str,
    pub what_is_title: &'a str,
    pub what_is_p1: &'a str,
    pub what_is_p2: &'a str,
    pub features_title: &'a str,
    pub feature_domain_management: &'a str,
    pub feature_domain_management_desc: &'a str,
    pub feature_user_management: &'a str,
    pub feature_user_management_desc: &'a str,
    pub feature_alias_management: &'a str,
    pub feature_alias_management_desc: &'a str,
    pub feature_backup_configuration: &'a str,
    pub feature_backup_configuration_desc: &'a str,
    pub feature_statistics_dashboard: &'a str,
    pub feature_statistics_dashboard_desc: &'a str,
    pub feature_dark_mode_support: &'a str,
    pub feature_dark_mode_support_desc: &'a str,
    pub technology_stack_title: &'a str,
    pub backend: &'a str,
    pub backend_desc: &'a str,
    pub database: &'a str,
    pub database_desc: &'a str,
    pub frontend: &'a str,
    pub frontend_desc: &'a str,
    pub templating: &'a str,
    pub templating_desc: &'a str,
    pub mail_server: &'a str,
    pub mail_server_desc: &'a str,
    pub deployment: &'a str,
    pub deployment_desc: &'a str,
    pub based_on_flurdy_title: &'a str,
    pub based_on_flurdy_desc: &'a str,
    pub read_guide: &'a str,
    pub github_project_title: &'a str,
    pub open_source: &'a str,
    pub open_source_desc: &'a str,
    pub view_repository: &'a str,
    pub view_repository_desc: &'a str,
    pub report_issues: &'a str,
    pub report_issues_desc: &'a str,
    pub pull_requests: &'a str,
    pub pull_requests_desc: &'a str,
    pub readme: &'a str,
    pub readme_desc: &'a str,
    pub version_information: &'a str,
    pub project_details: &'a str,
    pub version: &'a str,
    pub license: &'a str,
    pub maintainer: &'a str,
} 
