use crate::models::*;
use askama::Template;

#[derive(Template)]
#[template(path = "domain_backup/show.html")]
pub struct BackupShowTemplate {
    pub title: String,
    pub view_edit_settings: String,
    pub back_to_domains: String,
    pub backup_information: String,
    pub backup_details: String,
    pub domain: String,
    pub transport: String,
    pub status: String,
    pub created: String,
    pub modified: String,
    pub status_active: String,
    pub status_inactive: String,
    pub edit_backup: String,
    pub enable_backup: String,
    pub disable_backup: String,
    pub delete_backup: String,
    pub delete_confirm: String,
    pub delete_backup_disabled_tooltip: String,
    pub convert_to_domain: String,
    pub convert_to_domain_confirm: String,
    pub not_available: String,
    pub backup: Backup,
    // Cross-database domain information
    pub cross_database_info: Vec<crate::models::CrossDatabaseDomainInfo>,
    pub other_databases_header: String,
    pub other_databases_description: String,
    pub other_databases_database_label: String,
    pub other_databases_domain_type: String,
    pub other_databases_primary_domain: String,
    pub other_databases_backup_domain: String,
    pub other_databases_users_count: String,
    pub other_databases_aliases_count: String,
    pub status_enabled: String,
    pub status_disabled: String,
    // DNS section
    pub dns_section_header: String,
    pub dns_section_description: String,
    pub dns_lookup_button: String,
    pub dns_loading_label: String,
    // Relays section
    pub domain_relays: Vec<crate::models::Relay>,
    pub relays_header: String,
    pub relays_description: String,
    pub recipient_header: String,
    pub status_header_relay: String,
    pub enabled_header: String,
    pub no_relays_message: String,
    // Users section
    pub domain_users: Vec<crate::models::User>,
    pub users_header: String,
    pub users_description: String,
    pub user_id_header: String,
    pub user_enabled_header: String,
    pub users_empty_message: String,
    // Aliases section
    pub existing_aliases: Vec<crate::models::Alias>,
    pub existing_aliases_header: String,
    pub domains_mail_header: String,
    pub domains_destination_header: String,
    pub domains_enabled_header: String,
    pub no_required_aliases: String,
}

#[derive(Template)]
#[template(path = "domain_backup/form.html")]
pub struct BackupFormTemplate {
    pub title: String,
    pub form_error: String,
    pub form_domain: String,
    pub form_transport: String,
    pub form_active: String,
    pub placeholder_domain: String,
    pub placeholder_transport: String,
    pub tooltip_domain: String,
    pub tooltip_transport: String,
    pub tooltip_active: String,
    pub cancel: String,
    pub create_backup: String,
    pub update_backup: String,
    pub new_backup: String,
    pub edit_backup_title: String,
    pub backup: Option<Backup>,
    pub form: BackupForm,
    pub error: Option<String>,
}
