use askama::Template;

#[derive(Template)]
#[template(path = "error.html")]
pub struct ErrorTemplate {
    pub title: String,
    pub message: String,
    pub locale: String,
    pub content: String,
    // i18n fields
    pub app_title: String,
    pub app_subtitle: String,
    pub nav_dashboard: String,
    pub nav_domains: String,
    pub nav_aliases: String,
    pub nav_users: String,
    pub nav_relays: String,
    pub nav_relocated: String,
    pub nav_clients: String,
    pub nav_statistics: String,
    pub nav_reports: String,
    pub nav_config: String,
    pub nav_database_backup: String,
    pub nav_database: String,
    pub nav_wizard: String,
    pub nav_about: String,
    pub nav_contact: String,
    pub nav_logout: String,
    pub theme_toggle: String,
    pub language_selector: String,
    pub language_english: String,
    pub language_spanish: String,
    pub language_french: String,
    pub language_norwegian: String,
    pub language_german: String,
    pub language_dutch: String,
    pub language_italian: String,
    pub current_locale: String,
    pub current_db_label: String,
    pub current_db_id: String,
    pub relays_available: bool,
    pub relocated_available: bool,
    pub clients_available: bool,
    pub sidebar_main: String,
    pub sidebar_tables: String,
    pub sidebar_tools: String,
    pub sidebar_admin: String,
    pub sidebar_project: String,
    pub error_go_to_dashboard: String,
    pub error_go_back: String,
}

impl ErrorTemplate {
    pub async fn new(
        title: &str,
        message: &str,
        state: &crate::AppState,
        locale: &str,
        current_db_label: &str,
        current_db_id: &str,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        Ok(ErrorTemplate {
            title: title.to_string(),
            message: message.to_string(),
            locale: locale.to_string(),
            content: String::new(), // This will be filled by the template
            app_title: crate::i18n::get_translation(state, locale, "app-title").await,
            app_subtitle: crate::i18n::get_translation(state, locale, "app-subtitle").await,
            nav_dashboard: crate::i18n::get_translation(state, locale, "nav-dashboard").await,
            nav_domains: crate::i18n::get_translation(state, locale, "nav-domains").await,
            nav_aliases: crate::i18n::get_translation(state, locale, "nav-aliases").await,
            nav_users: crate::i18n::get_translation(state, locale, "nav-users").await,
            nav_relays: crate::i18n::get_translation(state, locale, "nav-relays").await,
            nav_relocated: crate::i18n::get_translation(state, locale, "nav-relocated").await,
            nav_clients: crate::i18n::get_translation(state, locale, "nav-clients").await,
            nav_statistics: crate::i18n::get_translation(state, locale, "nav-statistics").await,
            nav_reports: crate::i18n::get_translation(state, locale, "nav-reports").await,
            nav_config: crate::i18n::get_translation(state, locale, "nav-config").await,
            nav_database_backup: crate::i18n::get_translation(state, locale, "nav-database-backup")
                .await,
            nav_database: crate::i18n::get_translation(state, locale, "nav-database").await,
            nav_wizard: crate::i18n::get_translation(state, locale, "nav-wizard").await,
            nav_about: crate::i18n::get_translation(state, locale, "nav-about").await,
            nav_contact: crate::i18n::get_translation(state, locale, "nav-contact").await,
            nav_logout: crate::i18n::get_translation(state, locale, "nav-logout").await,
            theme_toggle: crate::i18n::get_translation(state, locale, "theme-toggle").await,
            language_selector: crate::i18n::get_translation(state, locale, "language-selector")
                .await,
            language_english: crate::i18n::get_translation(state, locale, "language-english").await,
            language_spanish: crate::i18n::get_translation(state, locale, "language-spanish").await,
            language_french: crate::i18n::get_translation(state, locale, "language-french").await,
            language_norwegian: crate::i18n::get_translation(state, locale, "language-norwegian")
                .await,
            language_german: crate::i18n::get_translation(state, locale, "language-german").await,
            language_dutch: crate::i18n::get_translation(state, locale, "language-dutch").await,
            language_italian: crate::i18n::get_translation(state, locale, "language-italian").await,
            current_locale: locale.to_string(),
            current_db_label: current_db_label.to_string(),
            current_db_id: current_db_id.to_string(),
            relays_available: state.config.is_relays_available(current_db_id),
            relocated_available: state.config.is_relocated_available(current_db_id),
            clients_available: state.config.is_clients_available(current_db_id),
            error_go_to_dashboard: crate::i18n::get_translation(state, locale, "error-go-to-dashboard").await,
            error_go_back: crate::i18n::get_translation(state, locale, "error-go-back").await,
            sidebar_main: crate::i18n::get_translation(state, locale, "sidebar-main").await,
            sidebar_tables: crate::i18n::get_translation(state, locale, "sidebar-tables").await,
            sidebar_tools: crate::i18n::get_translation(state, locale, "sidebar-tools").await,
            sidebar_admin: crate::i18n::get_translation(state, locale, "sidebar-admin").await,
            sidebar_project: crate::i18n::get_translation(state, locale, "sidebar-project").await,
        })
    }
}
