use crate::models::SearchResult;
use askama::Template;

#[derive(Template)]
#[template(path = "search/index.html", escape = "html")]
pub struct SearchPageTemplate<'a> {
    pub title: &'a str,
    pub description: &'a str,
    pub search_placeholder: &'a str,
    pub search_button: &'a str,
    pub search_results_title: &'a str,
    pub search_no_results: &'a str,
    pub search_no_results_description: &'a str,
    pub search_results_count: &'a str,
    pub search_time: &'a str,
    pub search_filter_types: &'a str,
    pub search_filter_enabled_only: &'a str,
    pub search_resource_type_domain: &'a str,
    pub search_resource_type_user: &'a str,
    pub search_resource_type_alias: &'a str,
    pub search_resource_type_backup: &'a str,
    pub search_resource_type_relay: &'a str,
    pub search_resource_type_relocated: &'a str,
    pub search_resource_type_client: &'a str,
    pub search_match_fields: &'a str,
    pub search_view_resource: &'a str,
    pub search_created: &'a str,
    pub search_modified: &'a str,
    pub status_enabled: &'a str,
    pub status_disabled: &'a str,
    pub query: String,
    pub selected_domain: bool,
    pub selected_user: bool,
    pub selected_alias: bool,
    pub selected_backup: bool,
    pub selected_relay: bool,
    pub selected_relocated: bool,
    pub selected_client: bool,
    pub enabled_only: bool,
    pub has_results: bool,
    pub total_count: usize,
    pub search_time_ms: u64,
    pub results: Vec<SearchResult>,
}
