-- Insert 50 random domains into the domains table
-- Generated for Sorting Office mail server

INSERT INTO domains (domain, transport, created, modified, enabled) VALUES
('acme-corp.com', 'virtual', NOW(), NOW(), 1),
('techstartup.io', 'virtual', NOW(), NOW(), 1),
('globaltrading.net', 'virtual', NOW(), NOW(), 1),
('innovationsolutions.org', 'virtual', NOW(), NOW(), 1),
('digitalmarketing.co', 'virtual', NOW(), NOW(), 1),
('webdesignstudio.com', 'virtual', NOW(), NOW(), 1),
('cloudservices.tech', 'virtual', NOW(), NOW(), 1),
('consultingpartners.biz', 'virtual', NOW(), NOW(), 1),
('ecommerceplatform.net', 'virtual', NOW(), NOW(), 1),
('softwaredevelopment.io', 'virtual', NOW(), NOW(), 1),
('financialservices.com', 'virtual', NOW(), NOW(), 1),
('healthcareclinic.org', 'virtual', NOW(), NOW(), 1),
('educationalinstitute.edu', 'virtual', NOW(), NOW(), 1),
('legalconsultants.law', 'virtual', NOW(), NOW(), 1),
('realestateagency.com', 'virtual', NOW(), NOW(), 1),
('restaurantchain.net', 'virtual', NOW(), NOW(), 1),
('manufacturingco.com', 'virtual', NOW(), NOW(), 1),
('retailstorechain.biz', 'virtual', NOW(), NOW(), 1),
('transportationlogistics.net', 'virtual', NOW(), NOW(), 1),
('energycompany.com', 'virtual', NOW(), NOW(), 1),
('mediaproduction.studio', 'virtual', NOW(), NOW(), 1),
('researchinstitute.org', 'virtual', NOW(), NOW(), 1),
('nonprofitcharity.org', 'virtual', NOW(), NOW(), 1),
('governmentagency.gov', 'virtual', NOW(), NOW(), 1),
('startupaccelerator.inc', 'virtual', NOW(), NOW(), 1),
('venturecapital.fund', 'virtual', NOW(), NOW(), 1),
('cryptocurrencyexchange.crypto', 'virtual', NOW(), NOW(), 1),
('blockchainplatform.io', 'virtual', NOW(), NOW(), 1),
('artificialintelligence.ai', 'virtual', NOW(), NOW(), 1),
('machinelearning.ml', 'virtual', NOW(), NOW(), 1),
('datascience.analytics', 'virtual', NOW(), NOW(), 1),
('cybersecurity.firm', 'virtual', NOW(), NOW(), 1),
('networkinfrastructure.net', 'virtual', NOW(), NOW(), 1),
('hostingprovider.host', 'virtual', NOW(), NOW(), 1),
('domainregistrar.reg', 'virtual', NOW(), NOW(), 1),
('webhostingcompany.com', 'virtual', NOW(), NOW(), 1),
('contentmanagement.cms', 'virtual', NOW(), NOW(), 1),
('customerrelations.crm', 'virtual', NOW(), NOW(), 1),
('enterpriseresource.erp', 'virtual', NOW(), NOW(), 1),
('supplychain.management', 'virtual', NOW(), NOW(), 1),
('humanresources.hr', 'virtual', NOW(), NOW(), 1),
('projectmanagement.pm', 'virtual', NOW(), NOW(), 1),
('qualityassurance.qa', 'virtual', NOW(), NOW(), 1),
('userexperience.ux', 'virtual', NOW(), NOW(), 1),
('userinterface.ui', 'virtual', NOW(), NOW(), 1),
('frontenddevelopment.dev', 'virtual', NOW(), NOW(), 1),
('backenddevelopment.api', 'virtual', NOW(), NOW(), 1),
('fullstackdevelopment.stack', 'virtual', NOW(), NOW(), 1),
('mobileappdevelopment.app', 'virtual', NOW(), NOW(), 1),
('gamedevelopment.game', 'virtual', NOW(), NOW(), 1),
('virtualreality.vr', 'virtual', NOW(), NOW(), 1),
('augmentedreality.ar', 'virtual', NOW(), NOW(), 1),
('internetofthings.iot', 'virtual', NOW(), NOW(), 1),
('smartcity.tech', 'virtual', NOW(), NOW(), 1),
('greenenergy.renewable', 'virtual', NOW(), NOW(), 1),
('sustainableliving.eco', 'virtual', NOW(), NOW(), 1);

-- Add some domains with different transport methods
INSERT INTO domains (domain, transport, created, modified, enabled) VALUES
('backupmx1.com', 'smtp:backup1.example.com', NOW(), NOW(), 1),
('backupmx2.net', 'smtp:backup2.example.com', NOW(), NOW(), 1),
('relaydomain.org', 'relay:relay.example.com', NOW(), NOW(), 1),
('forwarding.biz', 'forward:forward.example.com', NOW(), NOW(), 1);
